[package]
name = "suipredict_agent_policy"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "main" }
token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "main" }

[addresses]
suipredict = "0x0"
suipredict_agent_policy = "0x0"

[dev-addresses]
suipredict = "0x0"
suipredict_agent_policy = "0x0"
